// domain.js
const VALID_DOMAINS = {
    RETAIL: "nic2004:52110",
    FOOD_AND_BEVERAGE: "ONDC:RET11",
    FASHION: "ONDC:RET12",
    BEAUTY_AND_PERSONAL_CARE: "ONDC:RET13",
    ELECTRONICS: "ONDC:RET14",
    APPLIANCES: "ONDC:RET15",
};

module.exports = VALID_DOMAINS;
